services:
  postgres:
    image: postgres:15.2-alpine
    platform: linux/amd64
    shm_size: 1g
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - .docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}

  fastapi:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./app:/app